### ISSUE TITLE
kubernetes web UI dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#18]
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ should be available per vdc

**Comment by xmonader** [comment]
should be easy once we have access to the config, matter of applying the deployment file at the first look

**Comment by dmahmouali** [comment]
Following this [link](https://upcloud.com/community/tutorials/deploy-kubernetes-dashboard/)
### To apply the dashboard on your cluster:

1- Apply the dashboard chart on master:
 ```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
```
2- Create an Admin user:
  - create `admin.yaml` file
  ```
  apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
  ```
  - Apply using 
```
kubectl apply -f <path-to-file>/admin.yaml
```
  - Get token
  ```
  kubectl get secret -n kubernetes-dashboard $(kubectl get serviceaccount admin-user -n kubernetes-dashboard -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode
  ```

  #### this token will be used to sign in to the Kubernetes admin dashboard.
3- In your host apply 
```
kubectl proxy
```
4- Access the dashboard through the following [http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/](http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/)
#### Use the token previously obtained
![image](https://user-images.githubusercontent.com/36021484/99690985-65b64280-2a91-11eb-92a8-0b7711ef7374.png)
![image](https://user-images.githubusercontent.com/36021484/99691081-8088b700-2a91-11eb-9ee3-09d82d18a0aa.png)
