### ISSUE TITLE
Ingress helm charts with tls from our certificate authority server

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/vdc#69]

**Comment by AhmedHanafy725** [comment]
This can be done with `cert-manager`

### Prerequisites
1- Install cert-manager with its helm chart.
```bash
helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.1.0 --set installCRDs=true
```
2- Create cluster issuer.
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myacme
spec:
  acme:
    email: <your email>
    privateKeySecretRef:
      name: myacmesec # this secret will be used to issue the certificate
    server: <your acme server url>
    solvers:
    - http01:
        ingress:
          class: traefik # this should be changed in case of using another controller
```
### Steps
1- Add a record for the subdomain to the DNS.
2- Create a certificate in kubernetes for this domain.
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myacme
spec:
  secretName: myacmesec # the same secret in the cluster issuer
  dnsNames:
  - <domain> # the URL to your solution
  issuerRef:
    name: myacme # the name of the cluster issuer
    kind: ClusterIssuer
    group: cert-manager.io
```
3- Ingress the solution.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: myacme
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: <domain> # the URL to your solution
    http:
      paths:
      - path: /
        backend:
          serviceName: myservice # this should be changed to the service to your solution
          servicePort: 80 # this should be changed to the service port to your solution 
  tls:
  - hosts:
    - <domain> # the URL to your solution
    secretName: myacmesec # the same secret in cluster issuer
```
